// <auto-generated />
using System;
using System.Net;
using CarshiTow.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260502013902_TowYardRejectedAndStatusReason")]
    partial class TowYardRejectedAndStatusReason
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "au_state", "australian_state", new[] { "nsw", "vic", "qld", "wa", "sa", "tas", "nt", "act" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "damage_severity", "damage_severity", new[] { "low", "moderate", "severe", "probable_total_loss" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payout_status", "payout_status", new[] { "pending", "processing", "completed", "failed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "photo_category", "photo_category", new[] { "front", "rear", "left", "right", "interior", "engine", "undercarriage", "odometer", "other" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "photo_pack_status", "photo_pack_status", new[] { "draft", "pending_processing", "active", "paid", "expired", "flagged" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tow_yard_status", "tow_yard_status", new[] { "pending", "active", "suspended", "rejected" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "transaction_status", "transaction_status", new[] { "pending", "succeeded", "failed", "refunded", "partially_refunded" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_role", "user_role", new[] { "tow_yard_admin", "tow_yard_staff", "insurer", "crashify_admin", "crashify_support" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_status", "user_status", new[] { "active", "suspended", "pending_verification" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarshiTow.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_type");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("CarshiTow.Domain.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("fingerprint");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsTrusted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_trusted");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Fingerprint")
                        .IsUnique();

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("CarshiTow.Domain.Entities.OtpCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("code_hash");

                    b.Property<DateTime?>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer")
                        .HasColumnName("purpose");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Purpose", "CreatedAtUtc");

                    b.ToTable("otp_codes", (string)null);
                });

            modelBuilder.Entity("CarshiTow.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("CarshiTow.Domain.Entities.Payout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BankReference")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("bank_reference");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("GrossAmountCents")
                        .HasColumnType("integer")
                        .HasColumnName("gross_amount_cents");

                    b.Property<DateTime?>("InitiatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("initiated_at");

                    b.Property<int>("NetAmountCents")
                        .HasColumnType("integer")
                        .HasColumnName("net_amount_cents");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("period_end");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start");

                    b.Property<int>("ProcessingFeeCents")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("processing_fee_cents");

                    b.Property<int>("Status")
                        .HasColumnType("payout_status")
                        .HasColumnName("status");

                    b.Property<Guid>("TowYardId")
                        .HasColumnType("uuid")
                        .HasColumnName("tow_yard_id");

                    b.Property<short>("TransactionCount")
                        .HasColumnType("smallint")
                        .HasColumnName("transaction_count");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TowYardId");

                    b.ToTable("payouts", (string)null);
                });

            modelBuilder.Entity("CarshiTow.Domain.Entities.Photo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AiCategory")
                        .HasColumnType("photo_category")
                        .HasColumnName("ai_category");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<int>("FileSizeBytes")
                        .HasColumnType("integer")
                        .HasColumnName("file_size_bytes");

                    b.Property<decimal?>("GpsLat")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("gps_lat");

                    b.Property<decimal?>("GpsLng")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("gps_lng");

                    b.Property<short>("HeightPx")
                        .HasColumnType("smallint")
                        .HasColumnName("height_px");

                    b.Property<bool>("ManualCategoryOverride")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("manual_category_override");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mime_type");

                    b.Property<string>("OriginalS3Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_s3_key");

                    b.Property<Guid>("PackId")
                        .HasColumnType("uuid")
                        .HasColumnName("pack_id");

                    b.Property<string>("PreviewS3Key")
                        .HasColumnType("text")
                        .HasColumnName("preview_s3_key");

                    b.Property<short?>("QualityScore")
                        .HasColumnType("smallint")
                        .HasColumnName("quality_score");

                    b.Property<short>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("sort_order");

                    b.Property<DateTime?>("TakenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("taken_at");

                    b.Property<string>("ThumbnailS3Key")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_s3_key");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<short>("WidthPx")
                        .HasColumnType("smallint")
                        .HasColumnName("width_px");

                    b.HasKey("Id");

                    b.HasIndex("PackId");

                    b.ToTable("photos", (string)null);
                });

            modelBuilder.Entity("CarshiTow.Domain.Entities.PhotoPack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AiDamageDescription")
                        .HasColumnType("text")
                        .HasColumnName("ai_damage_description");

                    b.Property<string>("ClaimReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("claim_reference");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<int?>("DamageSeverity")
                        .HasColumnType("damage_severity")
                        .HasColumnName("damage_severity");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("FraudFlagged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("fraud_flagged");

                    b.Property<string>("FraudFlaggedReason")
                        .HasColumnType("text")
                        .HasColumnName("fraud_flagged_reason");

                    b.Property<DateTime?>("LinkExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("link_expires_at");

                    b.Property<string>("LinkToken")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("link_token");

                    b.Property<int>("LinkViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("link_view_count");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("PaidByEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("paid_by_email");

                    b.Property<short>("PhotoCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("photo_count");

                    b.Property<int>("PlatformFeeCents")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5500)
                        .HasColumnName("platform_fee_cents");

                    b.Property<short?>("QualityScore")
                        .HasColumnType("smallint")
                        .HasColumnName("quality_score");

                    b.Property<int>("Status")
                        .HasColumnType("photo_pack_status")
                        .HasColumnName("status");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("stripe_payment_intent_id");

                    b.Property<decimal?>("TotalLossProbability")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("total_loss_probability");

                    b.Property<int>("TotalPriceCents")
                        .HasColumnType("integer")
                        .HasColumnName("total_price_cents");

                    b.Property<Guid>("TowYardId")
                        .HasColumnType("uuid")
                        .HasColumnName("tow_yard_id");

                    b.Property<int>("TowYardPriceCents")
                        .HasColumnType("integer")
                        .HasColumnName("tow_yard_price_cents");

                    b.Property<string>("TowYardReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tow_yard_reference");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VehicleMake")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("vehicle_make");

                    b.Property<string>("VehicleModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("vehicle_model");

                    b.Property<string>("VehicleRego")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("vehicle_rego");

                    b.Property<int>("VehicleRegoState")
                        .HasColumnType("au_state")
                        .HasColumnName("vehicle_rego_state");

                    b.Property<string>("VehicleVin")
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)")
                        .HasColumnName("vehicle_vin");

                    b.Property<short>("VehicleYear")
                        .HasColumnType("smallint")
                        .HasColumnName("vehicle_year");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("LinkToken")
                        .IsUnique();

                    b.HasIndex("TowYardId");

                    b.ToTable("photo_packs", (string)null);
                });

            modelBuilder.Entity("CarshiTow.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("replaced_by_token_hash");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("CarshiTow.Domain.Entities.TowYard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Abn")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("abn");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address_line1");

                    b.Property<string>("BankAccountNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("bank_account_number");

                    b.Property<string>("BankBsb")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("bank_bsb");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("business_name");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("LastStatusChangeReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_status_change_reason");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<int?>("PlatformFeeOverride")
                        .HasColumnType("integer")
                        .HasColumnName("platform_fee_override");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("postcode");

                    b.Property<int>("State")
                        .HasColumnType("au_state")
                        .HasColumnName("state");

                    b.Property<int>("Status")
                        .HasColumnType("tow_yard_status")
                        .HasColumnName("status");

                    b.Property<string>("StripeConnectId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("stripe_connect_id");

                    b.Property<string>("Suburb")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("suburb");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string[]>("VerificationDocsUrl")
                        .HasColumnType("text[]")
                        .HasColumnName("verification_docs_url");

                    b.Property<DateTime?>("VerifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.Property<Guid?>("VerifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("verified_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("Abn")
                        .IsUnique();

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("VerifiedByUserId");

                    b.ToTable("tow_yards", (string)null);
                });

            modelBuilder.Entity("CarshiTow.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("InsurerEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("insurer_email");

                    b.Property<string>("InsurerOrgName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("insurer_org_name");

                    b.Property<string>("InvoiceS3Key")
                        .HasColumnType("text")
                        .HasColumnName("invoice_s3_key");

                    b.Property<int>("NetToTowYardCents")
                        .HasColumnType("integer")
                        .HasColumnName("net_to_tow_yard_cents");

                    b.Property<Guid>("PackId")
                        .HasColumnType("uuid")
                        .HasColumnName("pack_id");

                    b.Property<int>("PlatformFeeCents")
                        .HasColumnType("integer")
                        .HasColumnName("platform_fee_cents");

                    b.Property<int?>("RefundAmountCents")
                        .HasColumnType("integer")
                        .HasColumnName("refund_amount_cents");

                    b.Property<string>("RefundReason")
                        .HasColumnType("text")
                        .HasColumnName("refund_reason");

                    b.Property<Guid?>("RefundedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("refunded_by_user_id");

                    b.Property<int>("Status")
                        .HasColumnType("transaction_status")
                        .HasColumnName("status");

                    b.Property<string>("StripeChargeId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("stripe_charge_id");

                    b.Property<int>("StripeFeeCents")
                        .HasColumnType("integer")
                        .HasColumnName("stripe_fee_cents");

                    b.Property<string>("StripePaymentIntentId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("stripe_payment_intent_id");

                    b.Property<int>("TotalAmountCents")
                        .HasColumnType("integer")
                        .HasColumnName("total_amount_cents");

                    b.Property<int>("TowYardAmountCents")
                        .HasColumnType("integer")
                        .HasColumnName("tow_yard_amount_cents");

                    b.Property<Guid>("TowYardId")
                        .HasColumnType("uuid")
                        .HasColumnName("tow_yard_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PackId");

                    b.HasIndex("RefundedByUserId");

                    b.HasIndex("StripePaymentIntentId")
                        .IsUnique();

                    b.HasIndex("TowYardId");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("CarshiTow.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsMfaEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("mfa_enabled");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("MfaSecret")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("mfa_secret");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<int>("Role")
                        .HasColumnType("user_role")
                        .HasColumnName("role");

                    b.Property<int>("Status")
                        .HasColumnType("user_status")
                        .HasColumnName("status");

                    b.Property<Guid?>("TowYardId")
                        .HasColumnType("uuid")
                        .HasColumnName("tow_yard_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("TowYardId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CarshiTow.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("CarshiTow.Domain.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarshiTow.Domain.Entities.Device", b =>
                {
                    b.HasOne("CarshiTow.Domain.Entities.User", "User")
                        .WithMany("Devices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarshiTow.Domain.Entities.OtpCode", b =>
                {
                    b.HasOne("CarshiTow.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CarshiTow.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("CarshiTow.Domain.Entities.User", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarshiTow.Domain.Entities.Payout", b =>
                {
                    b.HasOne("CarshiTow.Domain.Entities.TowYard", "TowYard")
                        .WithMany("Payouts")
                        .HasForeignKey("TowYardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TowYard");
                });

            modelBuilder.Entity("CarshiTow.Domain.Entities.Photo", b =>
                {
                    b.HasOne("CarshiTow.Domain.Entities.PhotoPack", "Pack")
                        .WithMany("Photos")
                        .HasForeignKey("PackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pack");
                });

            modelBuilder.Entity("CarshiTow.Domain.Entities.PhotoPack", b =>
                {
                    b.HasOne("CarshiTow.Domain.Entities.User", "CreatedByUser")
                        .WithMany("CreatedPhotoPacks")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarshiTow.Domain.Entities.TowYard", "TowYard")
                        .WithMany("PhotoPacks")
                        .HasForeignKey("TowYardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("TowYard");
                });

            modelBuilder.Entity("CarshiTow.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("CarshiTow.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarshiTow.Domain.Entities.TowYard", b =>
                {
                    b.HasOne("CarshiTow.Domain.Entities.User", "OwnerUser")
                        .WithMany("OwnedTowYards")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarshiTow.Domain.Entities.User", "VerifiedByUser")
                        .WithMany("VerifiedTowYards")
                        .HasForeignKey("VerifiedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("OwnerUser");

                    b.Navigation("VerifiedByUser");
                });

            modelBuilder.Entity("CarshiTow.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("CarshiTow.Domain.Entities.PhotoPack", "Pack")
                        .WithMany("Transactions")
                        .HasForeignKey("PackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarshiTow.Domain.Entities.User", "RefundedByUser")
                        .WithMany("RefundedTransactions")
                        .HasForeignKey("RefundedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CarshiTow.Domain.Entities.TowYard", "TowYard")
                        .WithMany("Transactions")
                        .HasForeignKey("TowYardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pack");

                    b.Navigation("RefundedByUser");

                    b.Navigation("TowYard");
                });

            modelBuilder.Entity("CarshiTow.Domain.Entities.User", b =>
                {
                    b.HasOne("CarshiTow.Domain.Entities.TowYard", "TowYard")
                        .WithMany("StaffUsers")
                        .HasForeignKey("TowYardId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("CarshiTow.Domain.ValueObjects.HashedPassword", "Password", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("password_hash");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Password")
                        .IsRequired();

                    b.Navigation("TowYard");
                });

            modelBuilder.Entity("CarshiTow.Domain.Entities.PhotoPack", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("CarshiTow.Domain.Entities.TowYard", b =>
                {
                    b.Navigation("Payouts");

                    b.Navigation("PhotoPacks");

                    b.Navigation("StaffUsers");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("CarshiTow.Domain.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("CreatedPhotoPacks");

                    b.Navigation("Devices");

                    b.Navigation("OwnedTowYards");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("RefreshTokens");

                    b.Navigation("RefundedTransactions");

                    b.Navigation("VerifiedTowYards");
                });
#pragma warning restore 612, 618
        }
    }
}
